DNN_fluctuations:
  dirmodel: model_repository
  dirval: validation_new_random
  dirinput_bias: /data/tpcml/data_20200518/bias
  dirinput_nobias: /data/tpcml/data_20200518/nobias
  train_bias: true
  test_bias: true
  apply_bias: false
  diroutflattree: trees
  dirouthistograms: histograms
  tree_events: 20 # Number of events for validation (random events for nd_validation)
  use_partition: random # Whether the validator uses only the events from given partition
                        # 'random' is for choosing events randomly
  validate_model: true
  pdf_map_var: flucSC
  pdf_map_mean_id: 0
  grid_phi: 90
  grid_z: 17
  grid_r: 17
  selopt_input: 0 # 0 is use to train distorsions only for positive z-values
  selopt_output: 0 # 0 is use to predict distorsions only for positive z-values
  opt_train: [1, 1] #first position = meanSC, second = SCfluctuations
  opt_predout: [1, 0, 0] #R, Rphi, z output distorsion predictions
  nameopt_predout: [R, RPhi, Z] #R, RPhi, Z output distorsion predictions
  maxrandomfiles: 970 #this is the total number of random events generated
  range_mean_index: [0,26] # min and max index of mean SC configurations
  # events for training (include a mix of SC config)
  train_events: [10000] # 5000, 18000
  test_events: [1000] # 500, 1800
  apply_events: [7000] # 7000, 7000
  max_events: 27000 # number of all available events
  use_scaler: 0
  filters: 4
  pooling: 0
  batch_size: 27
  shuffle: false
  depth: 4
  batch_normalization: 0
  dropout: 0.0
  epochs: 20
  lossfun: mse
  metrics: mse
  adamlr: 0.001000
