DNN_fluctuations:
  dirmodel: model_new_random
  dirval: validation_new_random
  dirinput_bias: /data/tpcml/data_20200518/bias
  dirinput_nobias: /data/tpcml/data_20200518/nobias
  train_bias: true
  test_bias: true
  apply_bias: false
  diroutflattree: trees
  tree_events: 20 # Number of events for validation (random events for nd_validation)
  validate_model: true
  grid_phi: 90
  grid_z: 17
  grid_r: 17
  selopt_input: 0 # 0 is use to train distorsions only for positive z-values
  selopt_output: 0 # 0 is use to predict distorsions only for positive z-values
  opt_train: [1, 1] #first position = meanSC, second = SCfluctuations
  opt_predout: [1, 0, 0] #R, Rphi, z output distorsion predictions
  nameopt_predout: [R, Rphi, z] #R, Rphi, z output distorsion predictions
  maxrandomfiles: 970 #this is the total number of random events generated
  range_mean_index: [0,26] # min and max index of mean SC configurations 
  train_events: [900] # events for training (include a mix of SC config)
  test_events: [100]
  apply_events: [6000]
  max_events: 10000 # number of all available events
  use_scaler: 0
  filters: 4
  pooling: 0
  batch_size: 27
  shuffle: false
  depth: 4
  batch_normalization: 0
  dropout: 0.0
  epochs: 20
  lossfun: mse
  metrics: mse
  adamlr: 0.001000
