DNN_fluctuations:
  dirmodel: model
  dirval: validation
  dirinput:  /data/tpcml/data
  grid_phi: 90
  grid_z: 17
  grid_r: 17
  filters: 4
  pooling: 0
  batch_size: 8
  n_channels: 1
  shuffle: false
  depth: 4
  batch_normalization: 0
  side: 0
  dropout: 0.0
  use_scaler: 0
  distortion_type: 0 #0 is for checking R direction
  ephocs: 20
  rangeevent_train: [0,800]
  rangeevent_test: [801,970]
