DNN_fluctuations:
  dirmodel: model
  dirval: validation
  dirinput:  /data/tpcml/data
  grid_phi: 180
  grid_z: 33
  grid_r: 33
  #prepare the datasets
  selopt_input: 0 # this uses all input training data, no z-selection
  selopt_output: 0 # 0 is use to predict distorsions only for positive z-values
  opt_train: [1, 1] #first position = meanSC, second = SCfluctuations
  opt_predout: [1, 0, 0] #R, Rphi, z output distorsion predictions
  nameopt_predout: [R, Rphi, z] #R, Rphi, z output distorsion predictions
  rangeevent_train: [0,800]
  rangeevent_test: [801,970]
  use_scaler: 0
  #DNN configuration
  filters: 4
  pooling: 0
  batch_size: 8
  shuffle: false
  depth: 4
  batch_normalization: 0
  dropout: 0.0
  ephocs: 20
  lossfun: mse
  metrics: mse
  adamlr: 0.001000
