case: DNN_fluctuations
dotrain: false
doapply: false
doplot: false
dogrid: false
doprofile: false
docreatevaldata: true
docreatepdfmaps: true
docreatepdfmapforvariable: false
docreatepdfmapformeanid: false
domergepdfmaps: true
